import { Bot, RefreshCw, Download, CheckCircle, XCircle } from 'lucide-react';

export default function ReportViewer({ report, onRegenerate }) {
  if (!report) {
    return (
      <div className="bg-slate-900 border border-slate-800 rounded-lg p-12 text-center">
        <p className="text-slate-500">Select an incident to view its report</p>
      </div>
    );
  }

  const metrics = report.metrics || {};

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-lg overflow-hidden">
      <div className="p-5 border-b border-slate-800 flex items-center justify-between">
        <div>
          <h2 className="font-headline text-lg font-bold text-white">{report.title}</h2>
          <div className="flex items-center gap-2 mt-1">
            <span className="text-xs bg-blue-500/10 text-blue-400 border border-blue-500/20 px-2 py-0.5 rounded-full flex items-center gap-1">
              <Bot className="w-3 h-3" />
              Generated by AI
            </span>
            <span className="text-xs text-slate-500">{new Date(report.generated_at).toLocaleString()}</span>
          </div>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => onRegenerate?.(report.incident_id)}
            className="p-2 text-slate-400 hover:text-blue-400 hover:bg-slate-800 rounded-lg transition-colors"
            title="Regenerate"
          >
            <RefreshCw className="w-4 h-4" />
          </button>
          <button className="p-2 text-slate-400 hover:text-blue-400 hover:bg-slate-800 rounded-lg transition-colors" title="Download">
            <Download className="w-4 h-4" />
          </button>
        </div>
      </div>

      <div className="p-5 space-y-6">
        <section>
          <h3 className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-2">Summary</h3>
          <p className="text-sm text-slate-300 leading-relaxed">{report.summary}</p>
        </section>

        {report.timeline && report.timeline.length > 0 && (
          <section>
            <h3 className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-2">Timeline</h3>
            <ul className="space-y-1.5">
              {report.timeline.map((event, i) => (
                <li key={i} className="text-sm text-slate-400 flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-1.5 flex-shrink-0" />
                  {typeof event === 'string' ? event : `${event.timestamp}: ${event.event}`}
                </li>
              ))}
            </ul>
          </section>
        )}

        <section>
          <h3 className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-2">Root Cause Analysis</h3>
          <p className="text-sm text-slate-300 leading-relaxed">{report.root_cause}</p>
        </section>

        <section>
          <h3 className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-2">Action Taken</h3>
          <p className="text-sm text-slate-300">{report.action_taken}</p>
        </section>

        <section>
          <h3 className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-2">Metrics</h3>
          <div className="grid grid-cols-5 gap-3">
            <MetricCard label="MTTD" value={`${metrics.mttd_sec || 0}s`} />
            <MetricCard label="MTTR" value={`${metrics.mttr_sec || 0}s`} />
            <MetricCard label="Retries" value={metrics.retry_count ?? 0} />
            <MetricCard
              label="Automated"
              value={metrics.automated ? <CheckCircle className="w-4 h-4 text-emerald-400" /> : <XCircle className="w-4 h-4 text-red-400" />}
            />
            <MetricCard
              label="Escalated"
              value={metrics.escalated ? <XCircle className="w-4 h-4 text-red-400" /> : <CheckCircle className="w-4 h-4 text-emerald-400" />}
            />
          </div>
        </section>

        {report.recommendations && report.recommendations.length > 0 && (
          <section>
            <h3 className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-2">Recommendations</h3>
            <ol className="space-y-2">
              {report.recommendations.map((rec, i) => (
                <li key={i} className="flex items-start gap-3 text-sm">
                  <span className="w-5 h-5 rounded-full bg-blue-500/10 text-blue-400 flex items-center justify-center text-xs font-medium flex-shrink-0 mt-0.5">
                    {i + 1}
                  </span>
                  <span className="text-slate-300">{rec}</span>
                </li>
              ))}
            </ol>
          </section>
        )}
      </div>
    </div>
  );
}

function MetricCard({ label, value }) {
  return (
    <div className="bg-slate-800/50 border border-slate-700/50 rounded-lg p-3 text-center">
      <p className="text-xs text-slate-500 mb-1">{label}</p>
      <div className="text-sm font-medium text-slate-200 flex items-center justify-center">{value}</div>
    </div>
  );
}
